import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { InviteRecord } from './entities/invite-record.entity';
import { PointsService } from '../points/points.service';
import { TokenService } from '../token/token.service';
import { User } from '../user/entities/user.entity';

@Injectable()
export class InviteService {
  constructor(
    @InjectRepository(InviteRecord)
    private inviteRecordRepository: Repository<InviteRecord>,
    @InjectRepository(User)
    private userRepository: Repository<User>,
    private pointsService: PointsService,
    private tokenService: TokenService,
  ) {}

  async getMyCode(userId: number) {
    const user = await this.userRepository.findOne({ where: { id: userId } });
    return {
      code: user.inviteCode,
      link: `${process.env.DOMAIN || 'http://localhost'}?invite=${user.inviteCode}`,
      // qrCodeUrl would be generated by frontend
    };
  }

  async getStats(userId: number) {
    const direct = await this.inviteRecordRepository.count({
      where: { inviterId: userId, level: 1 },
    });
    const indirect = await this.inviteRecordRepository.count({
      where: { inviterId: userId, level: 2 },
    });

    // Calculate total reward
    const result = await this.inviteRecordRepository
      .createQueryBuilder('ir')
      .where('ir.inviterId = :userId', { userId })
      .select('SUM(ir.rewardPoints)', 'totalPoints')
      .addSelect('SUM(ir.rewardToken)', 'totalToken')
      .getRawOne();

    return {
      directCount: direct,
      indirectCount: indirect,
      totalReward: Number(result.totalToken || 0),
    };
  }

  async getRecords(userId: number) {
    return this.inviteRecordRepository.find({
      where: { inviterId: userId },
      order: { createdAt: 'DESC' },
    });
  }

  async bindInvite(userId: number, inviteCode: string) {
    // Find inviter by code
    const inviter = await this.userRepository.findOne({ where: { inviteCode } });
    if (!inviter) {
      return { success: false, message: 'Invalid invite code' };
    }

    // Update current user's inviter
    await this.userRepository.update(userId, { inviterId: inviter.id });

    // Record direct invite
    const record = this.inviteRecordRepository.create({
      inviterId: inviter.id,
      inviteeId: userId,
      level: 1,
      eventType: 'register',
      rewardPoints: 50,
      rewardToken: 10,
    });
    await this.inviteRecordRepository.save(record);

    // Reward direct inviter
    await this.pointsService.addPoints(inviter.id, 50, 1, 'invite');
    await this.tokenService.addTokens(inviter.id, 10, 5);

    // If inviter was invited by someone, give indirect reward
    if (inviter.inviterId) {
      const secondLevelInviter = await this.userRepository.findOne({
        where: { id: inviter.inviterId },
      });
      if (secondLevelInviter) {
        const indirectRecord = this.inviteRecordRepository.create({
          inviterId: secondLevelInviter.id,
          inviteeId: userId,
          level: 2,
          eventType: 'register',
          rewardPoints: 50,
          rewardToken: 0,
        });
        await this.inviteRecordRepository.save(indirectRecord);
        await this.pointsService.addPoints(secondLevelInviter.id, 50, 1, 'invite-indirect');
      }
    }

    return { success: true };
  }

  async processKycReward(userId: number) {
    // User completed KYC, reward inviter
    const user = await this.userRepository.findOne({ where: { id: userId } });
    if (!user || !user.inviterId) return;

    const inviter = await this.userRepository.findOne({ where: { id: user.inviterId } });
    if (!inviter) return;

    const record = this.inviteRecordRepository.create({
      inviterId: inviter.id,
      inviteeId: userId,
      level: 1,
      eventType: 'kyc',
      rewardPoints: 100,
      rewardToken: 50,
    });
    await this.inviteRecordRepository.save(record);

    await this.pointsService.addPoints(inviter.id, 100, 1, 'invite-kyc');
    await this.tokenService.addTokens(inviter.id, 50, 5);
  }

  async processFirstInvest(userId: number, amount: number) {
    const user = await this.userRepository.findOne({ where: { id: userId } });
    if (!user || !user.inviterId) return;

    if (amount >= 100) {
      const inviter = await this.userRepository.findOne({ where: { id: user.inviterId } });
      if (inviter) {
        const record = this.inviteRecordRepository.create({
          inviterId: inviter.id,
          inviteeId: userId,
          level: 1,
          eventType: 'first_invest',
          rewardPoints: 0,
          rewardToken: 50,
        });
        await this.inviteRecordRepository.save(record);
        await this.tokenService.addTokens(inviter.id, 50, 5);
      }
    }
  }

  async dailyAdBonus(inviteeId: number, points: number) {
    // 10% extra points to inviter
    const user = await this.userRepository.findOne({ where: { id: inviteeId } });
    if (!user || !user.inviterId) return;

    const extraPoints = Math.floor(points * 0.1);
    if (extraPoints > 0) {
      await this.pointsService.addPoints(user.inviterId, extraPoints, 3, 'invite-ad-bonus');

      const record = this.inviteRecordRepository.create({
        inviterId: user.inviterId,
        inviteeId: inviteeId,
        level: 1,
        eventType: 'ad_watch',
        rewardPoints: extraPoints,
        rewardToken: 0,
      });
      await this.inviteRecordRepository.save(record);
    }
  }
}
